# coding: utf-8

"""
    syntropy-controller

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AgentFiltersObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "agent_names": "list[TsoaPickAgentAgentNameOrAgentId_]",
        "versions": "list[TsoaPickAgentAgentVersion_]",
        "countries": "list[TsoaPickAgentAgentLocationCountry_]",
    }

    attribute_map = {
        "agent_names": "agentNames",
        "versions": "versions",
        "countries": "countries",
    }

    def __init__(self, agent_names=None, versions=None, countries=None):  # noqa: E501
        """AgentFiltersObject - a model defined in Swagger"""  # noqa: E501
        self._agent_names = None
        self._versions = None
        self._countries = None
        self.discriminator = None
        self.agent_names = agent_names
        self.versions = versions
        self.countries = countries

    @property
    def agent_names(self):
        """Gets the agent_names of this AgentFiltersObject.  # noqa: E501


        :return: The agent_names of this AgentFiltersObject.  # noqa: E501
        :rtype: list[TsoaPickAgentAgentNameOrAgentId_]
        """
        return self._agent_names

    @agent_names.setter
    def agent_names(self, agent_names):
        """Sets the agent_names of this AgentFiltersObject.


        :param agent_names: The agent_names of this AgentFiltersObject.  # noqa: E501
        :type: list[TsoaPickAgentAgentNameOrAgentId_]
        """
        if agent_names is None:
            raise ValueError(
                "Invalid value for `agent_names`, must not be `None`"
            )  # noqa: E501

        self._agent_names = agent_names

    @property
    def versions(self):
        """Gets the versions of this AgentFiltersObject.  # noqa: E501


        :return: The versions of this AgentFiltersObject.  # noqa: E501
        :rtype: list[TsoaPickAgentAgentVersion_]
        """
        return self._versions

    @versions.setter
    def versions(self, versions):
        """Sets the versions of this AgentFiltersObject.


        :param versions: The versions of this AgentFiltersObject.  # noqa: E501
        :type: list[TsoaPickAgentAgentVersion_]
        """
        if versions is None:
            raise ValueError(
                "Invalid value for `versions`, must not be `None`"
            )  # noqa: E501

        self._versions = versions

    @property
    def countries(self):
        """Gets the countries of this AgentFiltersObject.  # noqa: E501


        :return: The countries of this AgentFiltersObject.  # noqa: E501
        :rtype: list[TsoaPickAgentAgentLocationCountry_]
        """
        return self._countries

    @countries.setter
    def countries(self, countries):
        """Sets the countries of this AgentFiltersObject.


        :param countries: The countries of this AgentFiltersObject.  # noqa: E501
        :type: list[TsoaPickAgentAgentLocationCountry_]
        """
        if countries is None:
            raise ValueError(
                "Invalid value for `countries`, must not be `None`"
            )  # noqa: E501

        self._countries = countries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(AgentFiltersObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AgentFiltersObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
