# coding: utf-8

"""
    syntropy-controller

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ConnectionCreationBodyMesh(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"agent_ids": "list[AgentsObject]", "is_sdn_enabled": "bool"}

    attribute_map = {"agent_ids": "agent_ids", "is_sdn_enabled": "is_sdn_enabled"}

    def __init__(self, agent_ids=None, is_sdn_enabled=None):  # noqa: E501
        """ConnectionCreationBodyMesh - a model defined in Swagger"""  # noqa: E501
        self._agent_ids = None
        self._is_sdn_enabled = None
        self.discriminator = None
        self.agent_ids = agent_ids
        if is_sdn_enabled is not None:
            self.is_sdn_enabled = is_sdn_enabled

    @property
    def agent_ids(self):
        """Gets the agent_ids of this ConnectionCreationBodyMesh.  # noqa: E501


        :return: The agent_ids of this ConnectionCreationBodyMesh.  # noqa: E501
        :rtype: list[AgentsObject]
        """
        return self._agent_ids

    @agent_ids.setter
    def agent_ids(self, agent_ids):
        """Sets the agent_ids of this ConnectionCreationBodyMesh.


        :param agent_ids: The agent_ids of this ConnectionCreationBodyMesh.  # noqa: E501
        :type: list[AgentsObject]
        """
        if agent_ids is None:
            raise ValueError(
                "Invalid value for `agent_ids`, must not be `None`"
            )  # noqa: E501

        self._agent_ids = agent_ids

    @property
    def is_sdn_enabled(self):
        """Gets the is_sdn_enabled of this ConnectionCreationBodyMesh.  # noqa: E501


        :return: The is_sdn_enabled of this ConnectionCreationBodyMesh.  # noqa: E501
        :rtype: bool
        """
        return self._is_sdn_enabled

    @is_sdn_enabled.setter
    def is_sdn_enabled(self, is_sdn_enabled):
        """Sets the is_sdn_enabled of this ConnectionCreationBodyMesh.


        :param is_sdn_enabled: The is_sdn_enabled of this ConnectionCreationBodyMesh.  # noqa: E501
        :type: bool
        """

        self._is_sdn_enabled = is_sdn_enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(ConnectionCreationBodyMesh, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConnectionCreationBodyMesh):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
