# coding: utf-8

"""
    Syntropy network API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@syntropynet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V1AgentCoordinates(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "agent_id": "int",
        "agent_location_lat": "float",
        "agent_location_lon": "float",
    }

    attribute_map = {
        "agent_id": "agent_id",
        "agent_location_lat": "agent_location_lat",
        "agent_location_lon": "agent_location_lon",
    }

    def __init__(
        self, agent_id=None, agent_location_lat=None, agent_location_lon=None
    ):  # noqa: E501
        """V1AgentCoordinates - a model defined in Swagger"""  # noqa: E501
        self._agent_id = None
        self._agent_location_lat = None
        self._agent_location_lon = None
        self.discriminator = None
        self.agent_id = agent_id
        self.agent_location_lat = agent_location_lat
        self.agent_location_lon = agent_location_lon

    @property
    def agent_id(self):
        """Gets the agent_id of this V1AgentCoordinates.  # noqa: E501


        :return: The agent_id of this V1AgentCoordinates.  # noqa: E501
        :rtype: int
        """
        return self._agent_id

    @agent_id.setter
    def agent_id(self, agent_id):
        """Sets the agent_id of this V1AgentCoordinates.


        :param agent_id: The agent_id of this V1AgentCoordinates.  # noqa: E501
        :type: int
        """
        if agent_id is None:
            raise ValueError(
                "Invalid value for `agent_id`, must not be `None`"
            )  # noqa: E501

        self._agent_id = agent_id

    @property
    def agent_location_lat(self):
        """Gets the agent_location_lat of this V1AgentCoordinates.  # noqa: E501


        :return: The agent_location_lat of this V1AgentCoordinates.  # noqa: E501
        :rtype: float
        """
        return self._agent_location_lat

    @agent_location_lat.setter
    def agent_location_lat(self, agent_location_lat):
        """Sets the agent_location_lat of this V1AgentCoordinates.


        :param agent_location_lat: The agent_location_lat of this V1AgentCoordinates.  # noqa: E501
        :type: float
        """
        if agent_location_lat is None:
            raise ValueError(
                "Invalid value for `agent_location_lat`, must not be `None`"
            )  # noqa: E501

        self._agent_location_lat = agent_location_lat

    @property
    def agent_location_lon(self):
        """Gets the agent_location_lon of this V1AgentCoordinates.  # noqa: E501


        :return: The agent_location_lon of this V1AgentCoordinates.  # noqa: E501
        :rtype: float
        """
        return self._agent_location_lon

    @agent_location_lon.setter
    def agent_location_lon(self, agent_location_lon):
        """Sets the agent_location_lon of this V1AgentCoordinates.


        :param agent_location_lon: The agent_location_lon of this V1AgentCoordinates.  # noqa: E501
        :type: float
        """
        if agent_location_lon is None:
            raise ValueError(
                "Invalid value for `agent_location_lon`, must not be `None`"
            )  # noqa: E501

        self._agent_location_lon = agent_location_lon

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1AgentCoordinates, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1AgentCoordinates):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
