# coding: utf-8

"""
    Syntropy network API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@syntropynet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V1ConnectionServiceSubnet(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "agent_service_subnet_id": "int",
        "agent_connection_subnet_id": "int",
        "agent_connection_subnet_is_enabled": "bool",
        "agent_connection_subnet_error": "str",
        "agent_connection_subnet_status": "AgentConnectionSubnetStatuses",
    }

    attribute_map = {
        "agent_service_subnet_id": "agent_service_subnet_id",
        "agent_connection_subnet_id": "agent_connection_subnet_id",
        "agent_connection_subnet_is_enabled": "agent_connection_subnet_is_enabled",
        "agent_connection_subnet_error": "agent_connection_subnet_error",
        "agent_connection_subnet_status": "agent_connection_subnet_status",
    }

    def __init__(
        self,
        agent_service_subnet_id=None,
        agent_connection_subnet_id=None,
        agent_connection_subnet_is_enabled=None,
        agent_connection_subnet_error=None,
        agent_connection_subnet_status=None,
    ):  # noqa: E501
        """V1ConnectionServiceSubnet - a model defined in Swagger"""  # noqa: E501
        self._agent_service_subnet_id = None
        self._agent_connection_subnet_id = None
        self._agent_connection_subnet_is_enabled = None
        self._agent_connection_subnet_error = None
        self._agent_connection_subnet_status = None
        self.discriminator = None
        self.agent_service_subnet_id = agent_service_subnet_id
        self.agent_connection_subnet_id = agent_connection_subnet_id
        self.agent_connection_subnet_is_enabled = agent_connection_subnet_is_enabled
        self.agent_connection_subnet_error = agent_connection_subnet_error
        self.agent_connection_subnet_status = agent_connection_subnet_status

    @property
    def agent_service_subnet_id(self):
        """Gets the agent_service_subnet_id of this V1ConnectionServiceSubnet.  # noqa: E501


        :return: The agent_service_subnet_id of this V1ConnectionServiceSubnet.  # noqa: E501
        :rtype: int
        """
        return self._agent_service_subnet_id

    @agent_service_subnet_id.setter
    def agent_service_subnet_id(self, agent_service_subnet_id):
        """Sets the agent_service_subnet_id of this V1ConnectionServiceSubnet.


        :param agent_service_subnet_id: The agent_service_subnet_id of this V1ConnectionServiceSubnet.  # noqa: E501
        :type: int
        """
        if agent_service_subnet_id is None:
            raise ValueError(
                "Invalid value for `agent_service_subnet_id`, must not be `None`"
            )  # noqa: E501

        self._agent_service_subnet_id = agent_service_subnet_id

    @property
    def agent_connection_subnet_id(self):
        """Gets the agent_connection_subnet_id of this V1ConnectionServiceSubnet.  # noqa: E501


        :return: The agent_connection_subnet_id of this V1ConnectionServiceSubnet.  # noqa: E501
        :rtype: int
        """
        return self._agent_connection_subnet_id

    @agent_connection_subnet_id.setter
    def agent_connection_subnet_id(self, agent_connection_subnet_id):
        """Sets the agent_connection_subnet_id of this V1ConnectionServiceSubnet.


        :param agent_connection_subnet_id: The agent_connection_subnet_id of this V1ConnectionServiceSubnet.  # noqa: E501
        :type: int
        """
        if agent_connection_subnet_id is None:
            raise ValueError(
                "Invalid value for `agent_connection_subnet_id`, must not be `None`"
            )  # noqa: E501

        self._agent_connection_subnet_id = agent_connection_subnet_id

    @property
    def agent_connection_subnet_is_enabled(self):
        """Gets the agent_connection_subnet_is_enabled of this V1ConnectionServiceSubnet.  # noqa: E501


        :return: The agent_connection_subnet_is_enabled of this V1ConnectionServiceSubnet.  # noqa: E501
        :rtype: bool
        """
        return self._agent_connection_subnet_is_enabled

    @agent_connection_subnet_is_enabled.setter
    def agent_connection_subnet_is_enabled(self, agent_connection_subnet_is_enabled):
        """Sets the agent_connection_subnet_is_enabled of this V1ConnectionServiceSubnet.


        :param agent_connection_subnet_is_enabled: The agent_connection_subnet_is_enabled of this V1ConnectionServiceSubnet.  # noqa: E501
        :type: bool
        """
        if agent_connection_subnet_is_enabled is None:
            raise ValueError(
                "Invalid value for `agent_connection_subnet_is_enabled`, must not be `None`"
            )  # noqa: E501

        self._agent_connection_subnet_is_enabled = agent_connection_subnet_is_enabled

    @property
    def agent_connection_subnet_error(self):
        """Gets the agent_connection_subnet_error of this V1ConnectionServiceSubnet.  # noqa: E501


        :return: The agent_connection_subnet_error of this V1ConnectionServiceSubnet.  # noqa: E501
        :rtype: str
        """
        return self._agent_connection_subnet_error

    @agent_connection_subnet_error.setter
    def agent_connection_subnet_error(self, agent_connection_subnet_error):
        """Sets the agent_connection_subnet_error of this V1ConnectionServiceSubnet.


        :param agent_connection_subnet_error: The agent_connection_subnet_error of this V1ConnectionServiceSubnet.  # noqa: E501
        :type: str
        """
        if agent_connection_subnet_error is None:
            raise ValueError(
                "Invalid value for `agent_connection_subnet_error`, must not be `None`"
            )  # noqa: E501

        self._agent_connection_subnet_error = agent_connection_subnet_error

    @property
    def agent_connection_subnet_status(self):
        """Gets the agent_connection_subnet_status of this V1ConnectionServiceSubnet.  # noqa: E501


        :return: The agent_connection_subnet_status of this V1ConnectionServiceSubnet.  # noqa: E501
        :rtype: AgentConnectionSubnetStatuses
        """
        return self._agent_connection_subnet_status

    @agent_connection_subnet_status.setter
    def agent_connection_subnet_status(self, agent_connection_subnet_status):
        """Sets the agent_connection_subnet_status of this V1ConnectionServiceSubnet.


        :param agent_connection_subnet_status: The agent_connection_subnet_status of this V1ConnectionServiceSubnet.  # noqa: E501
        :type: AgentConnectionSubnetStatuses
        """
        if agent_connection_subnet_status is None:
            raise ValueError(
                "Invalid value for `agent_connection_subnet_status`, must not be `None`"
            )  # noqa: E501

        self._agent_connection_subnet_status = agent_connection_subnet_status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1ConnectionServiceSubnet, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1ConnectionServiceSubnet):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
