# coding: utf-8

"""
    Syntropy network API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@syntropynet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V1NetworkNacConfigConnection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "connect_to": "dict(str, V1NetworkNacConfigConnectionConnectTo)",
        "id": "int",
        "services": "list[str]",
        "state": "str",
        "type": "str",
    }

    attribute_map = {
        "connect_to": "connect_to",
        "id": "id",
        "services": "services",
        "state": "state",
        "type": "type",
    }

    def __init__(
        self, connect_to=None, id=None, services=None, state=None, type=None
    ):  # noqa: E501
        """V1NetworkNacConfigConnection - a model defined in Swagger"""  # noqa: E501
        self._connect_to = None
        self._id = None
        self._services = None
        self._state = None
        self._type = None
        self.discriminator = None
        if connect_to is not None:
            self.connect_to = connect_to
        if id is not None:
            self.id = id
        if services is not None:
            self.services = services
        if state is not None:
            self.state = state
        if type is not None:
            self.type = type

    @property
    def connect_to(self):
        """Gets the connect_to of this V1NetworkNacConfigConnection.  # noqa: E501


        :return: The connect_to of this V1NetworkNacConfigConnection.  # noqa: E501
        :rtype: dict(str, V1NetworkNacConfigConnectionConnectTo)
        """
        return self._connect_to

    @connect_to.setter
    def connect_to(self, connect_to):
        """Sets the connect_to of this V1NetworkNacConfigConnection.


        :param connect_to: The connect_to of this V1NetworkNacConfigConnection.  # noqa: E501
        :type: dict(str, V1NetworkNacConfigConnectionConnectTo)
        """

        self._connect_to = connect_to

    @property
    def id(self):
        """Gets the id of this V1NetworkNacConfigConnection.  # noqa: E501


        :return: The id of this V1NetworkNacConfigConnection.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V1NetworkNacConfigConnection.


        :param id: The id of this V1NetworkNacConfigConnection.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def services(self):
        """Gets the services of this V1NetworkNacConfigConnection.  # noqa: E501


        :return: The services of this V1NetworkNacConfigConnection.  # noqa: E501
        :rtype: list[str]
        """
        return self._services

    @services.setter
    def services(self, services):
        """Sets the services of this V1NetworkNacConfigConnection.


        :param services: The services of this V1NetworkNacConfigConnection.  # noqa: E501
        :type: list[str]
        """

        self._services = services

    @property
    def state(self):
        """Gets the state of this V1NetworkNacConfigConnection.  # noqa: E501


        :return: The state of this V1NetworkNacConfigConnection.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this V1NetworkNacConfigConnection.


        :param state: The state of this V1NetworkNacConfigConnection.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def type(self):
        """Gets the type of this V1NetworkNacConfigConnection.  # noqa: E501


        :return: The type of this V1NetworkNacConfigConnection.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V1NetworkNacConfigConnection.


        :param type: The type of this V1NetworkNacConfigConnection.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1NetworkNacConfigConnection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1NetworkNacConfigConnection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
