# coding: utf-8

"""
    Syntropy network API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@syntropynet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class V1NetworkNacConfigEndpoint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"id": "int", "services": "list[str]", "tags": "list[str]"}

    attribute_map = {"id": "id", "services": "services", "tags": "tags"}

    def __init__(self, id=None, services=None, tags=None):  # noqa: E501
        """V1NetworkNacConfigEndpoint - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._services = None
        self._tags = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if services is not None:
            self.services = services
        if tags is not None:
            self.tags = tags

    @property
    def id(self):
        """Gets the id of this V1NetworkNacConfigEndpoint.  # noqa: E501


        :return: The id of this V1NetworkNacConfigEndpoint.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V1NetworkNacConfigEndpoint.


        :param id: The id of this V1NetworkNacConfigEndpoint.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def services(self):
        """Gets the services of this V1NetworkNacConfigEndpoint.  # noqa: E501


        :return: The services of this V1NetworkNacConfigEndpoint.  # noqa: E501
        :rtype: list[str]
        """
        return self._services

    @services.setter
    def services(self, services):
        """Sets the services of this V1NetworkNacConfigEndpoint.


        :param services: The services of this V1NetworkNacConfigEndpoint.  # noqa: E501
        :type: list[str]
        """

        self._services = services

    @property
    def tags(self):
        """Gets the tags of this V1NetworkNacConfigEndpoint.  # noqa: E501


        :return: The tags of this V1NetworkNacConfigEndpoint.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this V1NetworkNacConfigEndpoint.


        :param tags: The tags of this V1NetworkNacConfigEndpoint.  # noqa: E501
        :type: list[str]
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(V1NetworkNacConfigEndpoint, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1NetworkNacConfigEndpoint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
