# coding: utf-8

"""
    syntropy-controller

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class VppCallableObjectArgs10(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"host_bridge": "str", "host_ip4_addr": "str", "addr": "str"}

    attribute_map = {
        "host_bridge": "host_bridge",
        "host_ip4_addr": "host_ip4_addr",
        "addr": "addr",
    }

    def __init__(self, host_bridge=None, host_ip4_addr=None, addr=None):  # noqa: E501
        """VppCallableObjectArgs10 - a model defined in Swagger"""  # noqa: E501
        self._host_bridge = None
        self._host_ip4_addr = None
        self._addr = None
        self.discriminator = None
        if host_bridge is not None:
            self.host_bridge = host_bridge
        self.host_ip4_addr = host_ip4_addr
        self.addr = addr

    @property
    def host_bridge(self):
        """Gets the host_bridge of this VppCallableObjectArgs10.  # noqa: E501


        :return: The host_bridge of this VppCallableObjectArgs10.  # noqa: E501
        :rtype: str
        """
        return self._host_bridge

    @host_bridge.setter
    def host_bridge(self, host_bridge):
        """Sets the host_bridge of this VppCallableObjectArgs10.


        :param host_bridge: The host_bridge of this VppCallableObjectArgs10.  # noqa: E501
        :type: str
        """

        self._host_bridge = host_bridge

    @property
    def host_ip4_addr(self):
        """Gets the host_ip4_addr of this VppCallableObjectArgs10.  # noqa: E501


        :return: The host_ip4_addr of this VppCallableObjectArgs10.  # noqa: E501
        :rtype: str
        """
        return self._host_ip4_addr

    @host_ip4_addr.setter
    def host_ip4_addr(self, host_ip4_addr):
        """Sets the host_ip4_addr of this VppCallableObjectArgs10.


        :param host_ip4_addr: The host_ip4_addr of this VppCallableObjectArgs10.  # noqa: E501
        :type: str
        """
        if host_ip4_addr is None:
            raise ValueError(
                "Invalid value for `host_ip4_addr`, must not be `None`"
            )  # noqa: E501

        self._host_ip4_addr = host_ip4_addr

    @property
    def addr(self):
        """Gets the addr of this VppCallableObjectArgs10.  # noqa: E501


        :return: The addr of this VppCallableObjectArgs10.  # noqa: E501
        :rtype: str
        """
        return self._addr

    @addr.setter
    def addr(self, addr):
        """Sets the addr of this VppCallableObjectArgs10.


        :param addr: The addr of this VppCallableObjectArgs10.  # noqa: E501
        :type: str
        """
        if addr is None:
            raise ValueError(
                "Invalid value for `addr`, must not be `None`"
            )  # noqa: E501

        self._addr = addr

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(VppCallableObjectArgs10, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VppCallableObjectArgs10):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
