name: PyPi

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools wheel
        sudo apt-get install jq
    - name: Build the wheel
      run: |
        export CI_SYNTROPY_VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
        python3 setup.py sdist bdist_wheel
        upload_url=$(curl -sL https://api.github.com/repos/SyntropyNet/syntropy-python-sdk/releases/latest | jq -r '.upload_url')
        echo ::set-env name=UPLOAD_URL::$upload_url
        cd dist
        echo ::set-env name=SYNTROPY_ASSET=`ls *.whl`
        cd -
    - name: Upload Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: dist/${{ env.SYNTROPY_ASSET }}
        asset_name: ${{ env.SYNTROPY_ASSET }}
        asset_content_type: application/zip
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        ls -al dist/
        echo python3 -m twine upload dist/*
