name: Tests

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip3 install virtualenv
        python3 virtualenv .venv && source .venv/bin/activate
        pip3 install --upgrade pip
        pip3 install --upgrade setuptools wheel
        pip3 install -r dev-requirements.txt
    - name: Build the wheel
      run: |
        source .venv/bin/activate
        python3 setup.py sdist bdist_wheel
    - name: Test with pytest
      run: |
        source .venv/bin/activate
        python3 -m pytest
    - name: Try installing the wheel
      run: |
        pip3 install `ls dist/*.whl`
        python3 -c "import syntropy_sdk"